package com.example.evoagent.report;

import com.example.evoagent.review.Finding;
import com.example.evoagent.review.ReviewReport;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class ReviewMarkdownGenerator {

    public String generate(ReviewReport report) {
        StringBuilder markdown = new StringBuilder();
        markdown.append("# AI PR Review Report\n\n");

        markdown.append("## Summary\n\n");
        markdown.append("- Repository: `").append(report.repo()).append("`\n");
        markdown.append("- PR: `#").append(report.prNumber()).append("`\n");
        markdown.append("- Status: `").append(report.status()).append("`\n");
        markdown.append("- Changed files: `").append(report.changedFileCount()).append("`\n");
        markdown.append("- Additions: `").append(report.totalAdditions()).append("`\n");
        markdown.append("- Deletions: `").append(report.totalDeletions()).append("`\n");
        markdown.append("- Findings: `").append(report.findings().size()).append("`\n\n");
        markdown.append(report.summary()).append("\n\n");

        appendContextFiles(markdown, report.contextFiles());
        appendFindings(markdown, report.findings());

        markdown.append("\n---\n");
        markdown.append("Generated by EvoAgent Code Review Agent.\n");
        return markdown.toString();
    }

    private void appendContextFiles(StringBuilder markdown, List<String> contextFiles) {
        markdown.append("## Context Used\n\n");
        if (contextFiles == null || contextFiles.isEmpty()) {
            markdown.append("No code context was retrieved.\n\n");
            return;
        }

        for (String file : contextFiles) {
            markdown.append("- `").append(file).append("`\n");
        }
        markdown.append("\n");
    }

    private void appendFindings(StringBuilder markdown, List<Finding> findings) {
        markdown.append("## Findings\n\n");
        if (findings == null || findings.isEmpty()) {
            markdown.append("No obvious issue found.\n");
            return;
        }

        for (int index = 0; index < findings.size(); index++) {
            Finding finding = findings.get(index);
            markdown.append("### ").append(index + 1).append(". ")
                    .append(nullToText(finding.level())).append(" - ")
                    .append(nullToText(finding.title())).append("\n\n");
            markdown.append("- File: `").append(nullToText(finding.file())).append("`\n");
            markdown.append("- Line: `").append(finding.line() == null ? "unknown" : finding.line()).append("`\n");
            markdown.append("- Type: `").append(nullToText(finding.type())).append("`\n\n");
            markdown.append("Evidence:\n\n");
            markdown.append(nullToText(finding.evidence())).append("\n\n");
            markdown.append("Suggestion:\n\n");
            markdown.append(nullToText(finding.suggestion())).append("\n\n");
        }
    }

    private String nullToText(String value) {
        if (value == null || value.isBlank()) {
            return "N/A";
        }
        return value;
    }
}
